### ISSUE TITLE
Feature: Invite User

### ISSUE THREAD

**Issue by elyseyao** [cs130-w22/Group-A1#30]
## User Story
As a user, I want to invite other users to events I own so that they can see the event in their events list.

## Detailed Description
By typing their username and hitting enter, users should be able to invite other users to events (if they haven't already been invited). Invited users should show up in the members list as an invited user.

## Acceptance Criteria
- [x] Given I invite myself, I should see an error.
- [x] Given I invite an existing member, I should see an error.
- [x] Given I invite a user who's already been invited, I should see an error.
- [x] Given I invite a nonexistent user, I should see an error.
- [x] Given I am not a member of the event, I should not be able to invite others.
- [x] Given I am a member of the event and send a valid invite, I should see a success message.
- [x] Given I have pending invites, they should show up on my home page.

**Comment by ultramarathon** [comment]
Can you add a check to remove users from invited if they join the event from a link?
![image](https://user-images.githubusercontent.com/50280292/154596563-260bef34-7936-4d9d-9076-798f9033939a.png)
